modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "replicore"
version = "${version}"
displayName = "RepliCore"
authors = "iMoonDay"
description = '''
Provides a method for item duplication
'''
#logoFile = ""

[[dependencies.replicore]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.replicore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

